Mellanox/rshim-user-space

rshim_pcie_lf.c
Include definitions for ntohl() and htonl().
Signed-off-by: Hans Petter Selasky <hps@selasky.org>
=> Build fix for FreeBSD.

man/bfrshim.1, src/rshim.c
the '-d' option is provided with a device name, the backend type
can be deduced from it thus no need for the '-b' option.
=> This commit simplify the command line for the '-d' option. When

src/rshim.h, src/rshim_pcie.c, src/rshim_pcie_lf.c
This commit enables the rshim PF device before trying to bind it.
It's needed on some platforms that the device is not enabled by
default somehow.
=> Enable pcie device during probing

src/rshim.c, src/rshim_pcie.c, src/rshim_pcie_lf.c
This commit adds domain id to the DEV_NAME in the misc file. It
also has some reliable changes to the drop_mode setting which
could be used during fw reset.
=> Add domain id to the DEV_NAME in the misc file

debian/copyright
This commit fixes the copyright format reported during debuild.
=> Fix the debian copyright format

configure.ac, debian/changelog, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c
This commit enhances rshim_pcie_enable in several ways.
- Add backend API enable_device for it. So other code could call
it when needed;
- Call the enable_device API when backend is recovered from
DROP_MODE.
- Check whether pcie is already being used bu another driver during
the probe.
=> Enhance rshim_pcie_enable function

Makefile.am, debian/changelog, etc/rshim.conf, man/rshim.8, rhel/rshim.spec.in, rshim.spec.in, src/rshim.c
This commit adds configuration file support (/etc/rshim.conf)
which can be used to configure the static mapping of rshim
device to rshim name as well as the rshim devices to be ignored.
=> Add configuration file support

src/rshim.c, src/rshim.h, src/rshim_pcie.c, src/rshim_pcie_lf.c, src/rshim_usb.c
This commit puts the livefish driver in drop mode by default to
avoid potential conflict with MFT tools. In such mode, only the
on-demand boot stream or reset command is allowed. All other read/
write requests will be ignored. This drop mode can be disabled by
sending command "DROP_MODE 0" to the misc file.
=> Put livefish driver in drop mode by default

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie_lf.c
This commit supports the display and configuring of the OPN string
for BlueField-2 cards. The setting is in the YU boot record which
persists during warm reboot and will be lost after cold reboot.
=> Display/configure OPN string for BlueField-2

src/rshim.c, src/rshim.h
BF-2 rev A0 requires a 'type 13' reset following each soft reset
in order to avoid a mesh deadlock.  This requires configuring
the type 13 reset modes at attach time and then after each soft
reset also write the reset 13 activation bit.
=> Add workaround to boot Viper rev A0 in LiveFish mode

src/rshim_pcie.c
This commit fixes a typo in mmap where MAP_LOCKED should be
set in the 'flags' argument instead of the 'prot' argument
of mmap().
=> rshim_pcie: Fix a typo in mmap

src/rshim_pcie.c, src/rshim_pcie_lf.c
If we are not able to find the pcie/pcie_lf device, we should return an error, so that rshim can catch that and abort.
Signed-off-by: Matthias Brugger <mbrugger@suse.com>
=> Fix return value if pcie or pcie_lf device not found

src/rshim.c, src/rshim.h, src/rshim_net.c, src/rshim_usb.c
This commit has the following robust fixes to solve issues found
on a setup with multiple USB rshim resetting in parallel.
1. rshim read might be not ready yet when USB is probed, which
caused RSH_SCRATCHPAD1 read fail. Some retry was added in
rshim_access_check().
2. Add more RSHIM_ERR() for error cases. Also change perror()
to RSHIM_ERR(), so it could be logged in syslog.
3. rshim_usb_disconnect() could be trigger by the hotplug
callback when USB is disconnected while doing synchronous
read/write(). Add mutex trylock mechanism to avoid mutex
deadlock. Later there will be another call to this function
again to cleanup the backend.
=> Some robust fixes for USB rshim

src/rshim.c
This commit adds the SIGINT handling, so it could be terminated by
'ctrl + c' when running in foreground.
Issue #27
=> Add SIGINT handling

rshim.spec.in
In case that the rshim server was not running, then installing the
new packages fails with error like:
Failed to stop rshim.service: Unit rshim.service not loaded.
error: %prein(rshim-2.0.5-4.x86_64) scriptlet failed, exit status 5
error: rshim-2.0.5-4.x86_64: install failed
Fixes: 0f1a303d106a ("Auto-start rshim service after installation")
Signed-off-by: Alaa Hleihel <alaa@nvidia.com>
=> rshim.spec.in: Stop rshim service only if it was running

src/rshim.c
This commit removes some checkings of the "is_boot_open" flag
so rshim console could display output when pushing the boot
stream.
=> Enable console output during boot stream pushing

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c
This commit checks the rshim accessibility when re-enabling it.
It fixes an issue in the following scenario:
1. rshim_pcie or rshim_pcie_lf is running;
2. MFT tool sets the rshim DROP_MODE to 1 and starts FW reset;
3. FW reset triggers the BlueField reset and thus USB reset;
4. USB rshim driver running on another host takes over this rshim
device (because the local rshim driver is still in DROP_MODE
which prevents the scratchpad register access. Thus the USB
rshim driver assumes no one is using the rshim device).
5. After FW reset, the rshim_pcie/rshim_pcie_lf driver resumes the
rshim access by setting DROP_MODE to 0.
6. Now there are two rshim drivers accessing the same rshim device
which caused unexpected behavior.
The fix is to check rshim accessibility at step 5 above to make
sure no …
=> Check rshim accessibility when re-enabling it

Makefile.am, man/Makefile.am, man/bfb-install.8, rshim.spec.in, scripts/bfb-install
This commit adds the bfb-install script for BFB install and status check.
Below is an example of command and output.
bfb-install --rshim rshim0 --bfb install.bfb --rootfs rootfs.tar.xz \
--config bf.cfg
Pushing bfb + cfg + rootfs
896MiB 0:09:12 [1.62MiB/s] [                    <=>          ]
Collecting BlueField booting status. Press Ctrl+C to stop…
INFO[BL2]: start
INFO[BL2]: no DDR on MSS0
INFO[BL2]: DDR POST passed
INFO[BL2]: UEFI loaded
INFO[BL31]: start
INFO[BL31]: runtime
INFO[UEFI]: eMMC init
INFO[UEFI]: eMMC probed
INFO[MISC]: Found bf.cfg
INFO[MISC]: Found tarball
INFO[MISC]: Start decomp
INFO[MISC]: Start install
INFO[MISC]: Rebooting
=> Add bfb-install script

src/rshim.c, src/rshim_fuse.c, src/rshim_pcie.c
This commit ignores the rshim access checking when global drop mode
is enabled in /etc/rshim.conf. It's requested for certain scenarios
where the rshim devices need to be visible in hypervisor when
drop_mode is enabled, at the same time it's pass-throughed to VM.
When drop_mode is globally enabled, it's user's responsibility to
make sure no parallel access from USB and PCIe to the same rshim.
=> Ignore rshim access checking when global drop mode is enabled

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c
DROP_MODE was added for live-fish mode, but turned out to be used
for other cases as well. Previously, some operations like pushing
boot stream is allowed in DROP mode, which is probmatic. For example,
it writes to the boot fifo, but the reading of scratch register does
nothing which causes potential boot fifo overflow for pcie rshim. This
commit disables all register access for pcie/pcie_lf for simplicity.
=> Don't allow any register access when DROP_MODE is set

src/rshim.c, src/rshim.h
This commit adds the workaround checking for Bluefield-2 REV-0, so the
workaround is only applied for A0 card. Or else it might think the card
is in livefish mode and cause infinite rebooting when due to mmio read
always returns 0 in secure boot mode.
=> Add workaround checking for Bluefield-2 REV-0

src/rshim.c
This commit has a fix for 5a174a13d559 to make it only applicable
for rshim/pcie. Commit 5a174a13d559 is supposed to fix an issue for
rshim/pcie and is not needed for USB. For USB, it's protected by the
RSH_SFLG_WRITING flag so only one read/write packet could be pending.
That commit also has side effect for USB that the rshim_fifo_tx_avail()
function could trigger USB read/write callback which try to take the
bd->ringlock again and caused potential dead-lock.
=> Fix 5a174a13d559 for potential USB deadlock

configure.ac, debian/changelog, rhel/rshim.spec.in, rshim.spec.in
This commit fixes the path of the config file for linux, which was
introduced in d484b8702157. The version is also updated.
=> Update version to 2.0.6-1

src/rshim.c
This commit refines some workaround condition.
For BOOT_MODE 0 issue, it should only apply to BF-1 card.
For BF-2 livefish reset workaround, it should only apply to A0 card.
=> Refine some workaround condition

src/rshim.c, src/rshim_net.c
This commit has some fixes to prevent intermittent hypervisor crash
when multiple cards reboot or push boot stream in parallel.
- Fix the return logic in rshim_is_livefish();
- Move the sleep inside rshim_boot_open() to prevent immediate
rshim access after SW reset and semaphore release;
- Clean up some log messages;
- Add a robust fix in rshim_net_rx() to drop error packets;
This commit fixes the return logic in rshim_is_livefish().
=> Several fixes to prevent hypervisor crash

src/rshim_net.c
The standard MTU size should be used instead of the max packet
size.
=> Fix MTU of the tmfifo_net0 interface

scripts/bfb-install
This commit enhances bfb-install to handle the 'DPU is ready'
message as an indication of installation completion.
=> bfb-install: Handle new message 'DPU is ready'

etc/rshim.conf, src/rshim.c, src/rshim.h, src/rshim_fuse.c
This commit makes the reset delay configurable instead of
hard-coded value. It also updates the USB reset delay to 3 seconds
to workaround some issue seen with USB hub.
=> Make the reset delay configurable

src/rshim_pcie.c, src/rshim_pcie_lf.c
=> Fix the crash issue for rshim over PCIe on BF1/BF2

src/rshim.h, src/rshim_usb.c
1) Modify rshim usb boot fifo code to take into account
BOOT FIFO COUNT. Only send a bulk transfer if there
is enough space in the boot fifo.
Note that there are instances where even if the BOOT
FIFO is empty, the number of bytes to be written can be
greater than the max available space in the BOOT FIFO.
For example, the write requests 0x4000 bytes while the
BOOT FIFO size is 0x2000.
2) Modify rshim usb tmfifo in code to take into account
the exact number of bytes to be sent by HW. get the
value from the interrupt transfer and pass it to
the bulk in transfer.
=> Support RSHIM USB for Mustang

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c, src/rshim_usb.c
This commits adds VFIO support for PCIe backend in order to support
the secure-boot host where kernel lock-down is enable thus direct
mmap() of the sysfs resource file is not allowed.
This commit also improves the 'DROP_MODE' handling. When DROP_MODE
is set, the PCIe resource will be released so the rshim PF could be
re-used for other purpose at runtime such as passing-through to other
VMs.
=> PCIe: VFIO support

src/rshim.c, src/rshim_pcie.c
Scratchpad1 needs to be cleared as an indication to NIC FW that
rshim is not active. This commit fixes the logic to move it before
unmapping the PCIe resource.
=> Clear scratchpad1 to 0 before PCI resources are unmapped

etc/rshim.conf, src/rshim.c, src/rshim.h, src/rshim_pcie.c
This commit adds interrupt polling for direct mmap() mode. Without
it the mlxfwreset sync-1 mode would fail due to FW waiting for the
interrupt ACK when rshim works in direct mmap() mode.
=> Add interrupt polling for direct mmap() mode

src/rshim_pcie.c
This commit adds a workaround fix to avoid kernel crash when unbinding
rshim from uio for some old linux kernel versions.
=> Avoid kernel crash when unbind rshim from uio

src/rshim.c, src/rshim.h, src/rshim_usb.c
This commit enables USB probing even there is no USB/rshim devices.
In such case, blocking call is used to avoid polling.
=> Detect new USB/rshim hot plugin

rshim.spec.in
In RHEL >= 8 systems, the fuse module is included in the package
kernel-modules-extra. ctyunos is somewhat of a RHEL8 clone, but includes
that module in the main kernel package. It does not have a
kernel-modules-extra package at all.
Signed-off-by: Tzafrir Cohen <nvidia@cohens.org.il>
=> Avoid kernel-modules-extra dependency on ctyunos

src/rshim.c, src/rshim_fuse.c, src/rshim_usb.c
This commit enhances the channel/address to access the 32-bit
CR-space via USB for BF3. When channel is bigger than 0xF, it'll
be interpreted as upper 16-bits of the linear CR-space address.
=> BF3: Support 32-bit CR-space access via USB

src/rshim_pcie.c
The rshim_pf device ID is changed to 0xc2d5 since the previously
used 0xc2d4 was reserved for BlueField3-Lx. Continue to support
both IDs for now in order to stay compatible with older FW.
=> Mustang: Change rshim_pcie Device ID

etc/rshim.conf, src/rshim.c, src/rshim.h, src/rshim_pcie.c
VFIO/UIO is currently enabled by default and will be selected
automatically. Some users would like to specify which one to use
or diable. This commit adds configuration option in rshim.conf
to disable them as needed by setting PCIE_HAS_VFIO / PCIE_HAS_UIO
to 0 in rshim.conf.
=> Add configuration option to enable/disable PCIe VFIO/UIO

src/rshim_pcie.c
This commit adds some robust check to avoid the race of the rshim_regs
pointer acess when stopping the process, which was found by restarting
the rshim service in a loop.
=> Avoid potential race when stopping the rshim process

etc/rshim.conf, src/rshim.c
The 'BOOT_TIMEOUT' configuration parameter is used to detect ARM stuck/crash that it hasn't polled the boot fifo for such time. It's reported that when redfish is enabled it could take more than 100s doing something without reading the boot stream. Adjust the default value to avoid the false error.
=> Adjust default boot timeout to 150s

src/rshim_usb.c
Function rshim_usb_disconnect() will be called during USB disconnect which releases some buffer pointers, while rshim_usb_backend_cancel_req() is called during console release which tries to use these pointers. So it'll cause crash if console is released after USB disconnect and before the reconnect. This commit adds a check to avoid such issue.
=> Fix a potential NULL pointer access during USB disonnect

src/rshim.h
This commit adds a new bad-access code detected recently so rshim driver could detect the failure to avoid stuck in loops.
=> rshim-pcie: add a new bad-access code

debian/control
This commit adds the libfuse2 dependency so it could be installed together with the driver. This issue was found when installing rshim driver on Ubuntu 22.04.
=> Add dependency of libfuse2

src/rshim_fuse.c
rshim register might be not accessible in several cases such as DROP_MODE is set or during NIC FW reset. This commit removes the failure/return checking of read_rshim() when displaying the misc file. So other tools or regression scripts won't break. The error message is preserved to show what's happening.
RM #3228372
=> rshim_fuse: display misc file even when rshim is not accessible

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c, src/rshim_regs.h, src/rshim_usb.c
This commit adds 4B access and OPN display for BF3.
=> BF3: Support 4B access for PCIe

etc/rshim.conf, src/rshim_pcie.c
External tools or regression script might toogle the value of DROP_MODE in the rshim misc file, which will trigger function call rshim_pcie_mmap_uio() when UIO is used, thus reopening the /dev/uio file and causing a file handler leak. This commit adds a check to avoid such case. It does't close the handler because the interrupt thread might be still using it.
This commit also adds some comments in the configuration example rshim.conf.
=> Avoid opening /dev/uio multiple times

configure.ac, debian/changelog, rhel/rshim.spec.in, rshim.spec.in, src/rshim.c
Starting from this build, the dash is removed from tags accoring to https://github.com/Mellanox/rshim-user-space/issues/105.
Fixes #105
=> Update version to 2.0.7

src/rshim_pcie.c
rshim pcie could use VFIO and UIO for memory map, and fall-back to direct-mapping when both fail. This commit adjusts the fall-back condition, so it doesn't have to go through UIO since UIO might be not available on some setups.
RM #3468188
=> rshim_pcie: Fix the fall-back logic of direct-mapping

scripts/bfb-install
This commit returns correct failure code so automation scripts could check it properly.
=> bfb-install: Return failure code

src/rshim_fuse.c
This commit adds UPTIME display in misc file which shows the time in seconds since last warm reset.
=> BF3: Add UPTIME display in seconds

configure.ac, rshim.spec.in, src/rshim_fuse.c
Some Linux distributions only have fuse3 available. This commit adds support to detect and use fuse3.
RM #3623445
=> Add fuse3 support

scripts/bfb-install
This commit adds BFB completion condition check for enhanced NIC mode. It also moves the check to the beginning of the loop to detect the completion of enhanced NIC mode right after BFB push.
RM #3669288
=> Add BFB completion condition for enhanced NIC mode

rshim.spec.in
This commit temporarily remove the build dependency on libfuse to unblock some build regression which is not able to handle such syntax. It'll be added back later once the build environment is fixed.
=> Remove the libfuse build dependency

src/rshim.c
This commit fixed a checking for oversized packet which was introduced by commit 9f19cfb4a75687ae. It should only be applied to network packet.
=> Fix incorrect console message drop

README.md, src/rshim_fuse.c, src/rshim_regs.h
This is for the feature of [[Feature #3751187]: [Design] - [BF3][NIC Mode] Secure NIC mode](https://redmine.mellanox.com/issues/3751187). Outputting a mode indication to "/dev/rshimN/misc:" device node for the PCIe host when the NIC FW is in locked mode.
=> Output SECURE_NIC_MODE status in /dev/rshimN/misc

man/bfb-install.8, scripts/bfb-install
* Added remote rshim so we can run BFB update remotely. Here "remote" means the RSHIM driver is running in a different processor other than the processor initiating bfb-install. Both processors will be in the same network, though they could be inside the same server enclosure. The remote rshim is invoked with an updated syntax for the "--rshim" option.
* Improved BMC update speed if using netcat instead of scp to transmit the BFB data. This is done by specifying a optional new argument of "--remote-mode" with "nc" or "ncpipe" values.
=> Update scripts/bfb-install to support remote rshim and improve speed

src/rshim.c, src/rshim.h, src/rshim_fuse.c
This commit has two robust changes for DROP_MODE which is set to disable access to rshim.
- Call rshim_fifo_sync() to send zero-padding to peer side in case the DROP_MODE was enabled when the peer side is in the middle of receiving a packet.
- Clear the net_rx_len & net_tx_len to abort the current Rx & Tx when DROP_MODE is cleared.
RM #3823043
=> Add some robust fixes for the DROP_MODE

src/rshim.c, src/rshim.h, src/rshim_fuse.c
Since DROP_MODE is a special mode to block rshim access, there could be leftover data in the Rx FIFO which causes packet out-of-sync when rshim access is re-enabled. This commit avoid such issue by draining the Rx FIFO when DROP_MODE is cleared.
=> DROP_MODE: sync-up the Rx FIFO when clearing DROP_MODE

src/rshim.c
When pushing BFB from PCIe host, the driver will reset the chip then start to push boot stream after a delay. The delay was added with the mutex taken, which blocks other access including the periodic timer which updates scratchpad1 for ownership, while at the same time the rshim driver on DPU BMC could be activated and take the ownership during this delay. This commit adds 0.5s initial delay for the ARM reset, then release the mutex so the timer function could kick in to update the scratchpad1 register. The original boot stream delay is moved after releasing the mutex.
RM #3835006
=> Avoid a race of rshim ownership during bfb push

scripts/bfb-install
This commit addresses a bug where local host's IP addresses were incorrectly resolved when there are multiple routing hops between local host and remote rshim host.
=> Fix issue with incorrect IP address resolution in multi-hop routing scenarios

src/rshim.c
This is to address https://redmine.mellanox.com/issues/3881613 (FR #3881613 - RSHIM 0 SCRATCHPAD1 register read error seen in rshim log on bfb push)
=> Lower log level for register read errors as it's normal during reset

src/rshim.c, src/rshim.h, src/rshim_pcie.c
This pull has two robust fixes:
1. Add a check to avoid polling the 'blocked' state during reset;
2. Adjust the default PCIe reset delay to avoid boot stream corruption.
=> some robust fixes

src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c, src/rshim_regs.h, src/rshim_usb.c
This one is needed by RM #3892195 to support register read/write by pcie-lf driver. 
During the testing for livefish driver, two more fixes are also made:
1. Cleanup the code to remove the workaround for BF2 A0;
2. Add a check to do 'blocked' state checking only for PCIe backend.
=> pcie-lf driver enhancement to support register read/write with the bf_reg.py script

Makefile.am, man/Makefile.am, man/bf-reg.8, rshim.spec.in, scripts/bf-reg, scripts/bfb-install
This commit enables runtime image upgrade with the '-u' option, so image can be pushed without resetting the DPU. It'll expect rshim log 'Runtime upgrade finished' to exit the polling.
A utility script bf_reg.pl is added to access registers via rshim. It's in perl, so it could be used on DPU BMC as well by default.
It also has a new misc command 'CLEAR_ON_READ'. If set, the rshim log will be cleared after read.
=> bfb-install: add runtime image support

src/rshim.h, src/rshim_fuse.c, src/rshim_log.c
This command adds the 'CLEAR_ON_READ' misc command. Once set, the rshim log will be cleared after read.
=> misc: add 'CLEAR_ON_READ' command

scripts/bfb-install
This commit adds cleanup code for runtime update, so SP2.BIT2 could be always cleared when script completes.
=> bfb-install: add cleanup code for runtime update

scripts/bfb-install
rshim log buffer is only 1KB in size. Once full, it'll discard the rest of messages which might contain important messages for errors or installation completion. This commit enables CLEAR_ON_READ as a quick workaround to clear the log buffer after read during the polling of installation status. Since the log is cleared from the log buffer during bfb-install, file /tmp/bfb-install.log is create to preserve these logs in case it might be needed.
In next release, it's preferred to update the kernel driver on DPU side, such as by adding a new local buffer for  Linux logging, or making the rshim log as circular buffer for logs from Linux.
RM #3908498
=> bfb-install: Enable CLEAR_ON_READ

scripts/bfb-install
This commit contains enhancement for BFB installation in NIC mode.
- Poll for 'In Enhanced NIC mode' message as installation completion.
- Unbind mlx5_core driver before installation, bind it back once it's done.
- Disable rshim log 'CLEAR_ON_READ' after seeing the installation completion indication.
RM #3955968 #3956059
=> bfb-install: enhancement for NIC mode

etc/rshim.conf, man/rshim.8, src/rshim.c, src/rshim.h, src/rshim_fuse.c, src/rshim_pcie.c, src/rshim_pcie_lf.c, src/rshim_usb.c
When Rshim driver finds another backend has attached to the rshim device, it
will enter drop mode. In this mode, user can echo a "FORCE_CMD 1" to
the misc file to request rshim ownership from the other backend.
Similarly, user can also send a one-time Force command using command option of
"--force", or setting "FORCE_CMD" to 1 in rshim.conf.
If Rshim driver is able to attach to the rshim device, it will monitor
the SP1 for incoming "RequestOwnership" command, and release rshim when
that command is found.
RM: 3679848
=> Add ownership transfer feature

scripts/bfb-install
This patch prevents from many SSH password prompts when public key authentication for SSH hasn't been setup. We will just bail out early in that case.
RM: 3858869 (https://redmine.mellanox.com/issues/3858869)
=> Exit with error if running remote bfb-install without password-less root SSH

scripts/bfb-install
Bing/Unbind mlx5_core driver output redirection synatx doesn't work The Unbind was trigger in background causing the driver to crash So therefore I remove the output redirection synatx and test it on baby-isr-1 and it works
=> bfb-install: fix for NIC mode

etc/rshim.conf, man/rshim.8, src/rshim.c
Make BMC happy by only creating the `/dev/rshim<N>` directory when running with `-F, --force` or configured such in `rshim.conf`.
RM #3987930
=> Allow /dev/rshim<N> devfs creation only with --force option on

scripts/bfb-install
This commit fixes check_nic_mode() in the bfb-install script which is used to determination the completion of the installation and is only applicable to BF3.
RM #4005240
=> bfb-install: fix NIC_MODE installation for BF2

debian/postinst
1. In older version before 2.0.30, the debian/rules in the source code is written such that the rshim service is auto enabled. After installation, Ubuntu auto-generates these  files among others:
```
-rwxr-xr-x 1 root root 1251 Apr  5 10:41 /var/lib/dpkg/info/rshim.postinst*
-rwxr-xr-x 1 root root  642 Apr  5 10:41 /var/lib/dpkg/info/rshim.postrm*
-rwxr-xr-x 1 root root  206 Apr  5 10:41 /var/lib/dpkg/info/rshim.prerm*
```
The postrm will mask the service and postinst will unmask the service. So if the user run "apt remove", it will mask rshim but after running "apt install", it will be unmasked.
3. Then in 2.0.30, I introduced this change to disable rshim by default, With this change, the rshim deb package installation will no longer generate postrm and prerm. And the postinst no longer …
=> fix issue on Ubuntu that rshim service is masked after upgrade since 2.0.30

scripts/bfb-install
Prevent bfb-install exit filter to match "Rebooting BMC.." string.
RM #4047597
=> Fix premature bfb-install exit when rebooting BMC

etc/rshim.conf, src/rshim.c
The 'BOOT_TIMEOUT' configuration parameter is used to detect ARM stuck/crash when it hasn't polled the boot FIFO for such time. It's found in a certain server that redfish related activities could pause reading boot stream for more than 180s. Adjust the default value to prevent such error.
RM #3830033
=> Adjust default boot timeout to 200s

etc/rshim.conf, src/rshim.c
The 'BOOT_TIMEOUT' configuration parameter is used to detect ARM stuck/crash when it hasn't polled the boot FIFO for such time. It's found in a certain server that redfish related activities could pause reading boot stream for more than 200s. Adjust the default value to prevent such error.
RM #3830033
=> Increase default boot timeout to 300s

src/rshim.c
The 'BOOT_RESET_SKIP' debug command is used to skip ARM reset when pushing a BFB, which is used during palladium test to save reboot time. With minor change to skip the automatic 'BOOT_MODE' setting as well, this command can be used to simulate eMMC boot which could be very useful to upgrade preboot BSP in NIC mode because it doesn't requires power-cycle after the upgrade.
Below are steps example to push preboot_install.bfb in NIC mode without affecting DRAM allocation:
echo "BOOT_MODE 0" > /dev/rshim0/misc
echo "SW_RESET 1" > /dev/rshim0/misc
echo "BOOT_MODE 1" > /dev/rshim0/misc
echo "BOOT_RESET_SKIP 1" > /dev/rshim0/misc
cat preboot_install.bfb > /dev/rshim0/boot
echo "BOOT_RESET_SKIP 0" > /dev/rshim0/misc
RM #4134329
=> Use BOOT_RESET_SKIP command to simulate eMMC boot

etc/rshim.conf, src/rshim.h
This commit updates the default USB timeout to workaround an issue with curl not handling the returning error code when using command 'curl xxx -o /dev/rshim0/boot' to inject the boot stream while BlueField SoC is busying for more than 20 seconds.
RM #4128189
=> Update default USB timeout

configure.ac
Fix the following syntax errors:
...
checking for fuse... yes
./configure: line 5243: test: =: unary operator expected
checking for pthread_create in -lpthread... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
...
I will not check it for Freebsd or other OS, but there is obviously something wrong with the syntax.
=> configure: fix fuse errors

src/rshim.c
Ignore PID creation when using "-d" to attaching to a rshim device directly.
For instance, this is allowed:
rshim -d pcie-0000:b1:00.2 -i 0
rshim -d pcie-0000:17:00.2 -i 1
RM #4183269
=> Allow multi rshim processes for dev attachment.

rshim.spec.in, scripts/rshim-fix.te
This issue was discovered on RHEL 9.5 on AARCH64, but it should be applicable to all platforms with SELinux in enforcing mode.
RM #4170376
=> Fix SELinux policy in enforcing mode

.github/workflows/ci.yml, scripts/build-rpm, scripts/get-changelog, scripts/get-ver
- Every commit will cause a pipeline to run.
- The pipeline do the following for each type (x64/arm64 deb/rpm):
- Build the deb/rpm
- Test the deb/rpm:
- Run the deb/rpm installation
- Run `rshim --version` to check instalation
- Artifacts can be downloaded from the link in the pipeline log
- A tag push will additionaly cause a release to be build and shown in the Release page at: https://github.com/Mellanox/rshim-user-space/releases
RM #4194972
=> Add GitHub pipeline to create deb/rpm packages

.github/workflows/ci.yml
The previous `ncipollo/release-action` is not allowed in NVIDIA enterprise GitHub account
=> Use softprops/action-gh-release for release

rshim.spec.in
Commit 69815e92738f adjusts the dependency to use kernel-uek-core, but it is only available since UEK Release 7. Thus the RPM install is broken in racle Linux 8.6 which uses UEK Release 6. This commit adjusts to use kernel-uek-core since Oracle Linux 9. For Oracle Linux 8, kernel-modules-extra still exists which contains the cuse module.
RM #4253481
=> Fix RPM dependency on Oracle Linux 8.6

scripts/bfb-install
Exiting the script results in rshim log not printed on to the screen missing the reason why the install failed.
RM #4328011
=> bfb-install: don't exit script when rshim install fails

man/rshim.8, src/rshim.c, src/rshim.h, src/rshim_cmdmode.c, src/rshim_fuse.c
Syntax:
./rshim --help
...
-c, --cmdmode             run in command line mode
-r, --reg <addr.[32|64] [value]> set debug mode
-i, --index               use device path /dev/rshim<i>/
...
Example:
./rshim -c -i 0 -r 0x13000c48.64
[0x13000c48] -> 0x0000000000000018
./rshim -c -i 0 -r 0x13000c48.64 0x10018
[0x13000c48] <- 0x0000000000010018
UEFI debugging can be enabled now from PCIe host for any rshim:
./rshim -c -i <N> -s 1
RM #4345395
=> Enhance command line for register read/write

scripts/bfb-install
This commit set NIC mode in BREADCRUMB.BIT31 to solve some upgrade issue when NIC_FW is too old.
=> Use BREADCRUMB.BIT31 to indicate NIC mode

scripts/bfb-install
This commit has changes to support trimmed NIC_FW by adding the signature back which will be handled by CX ExpansionRom driver ( version 14.38.0010 or above).
RM #4330047
=> bfb-install: Support trimmed NIC_FW

.github/workflows/ci.yml
GitHub's cloud VM has limited resources such that it may run into issues in linking when "lto" flag is on, as Link Time Optimization uses a lot of resources. Disabling lto solves the issue.
RM #4362233
https://redmine.mellanox.com/issues/4362233
=> Fix occasional github pipeline docker error

scripts/bfb-install, src/rshim_cmdmode.c
Currently BMC username/password is needed to do upgrade in DPU mode. This information is not provided when BFB is generated from PLDM. This commit packs the bf.cfg into the generated BFB for this purpose which is provided with argument '-c bf.cfg'.
This commit also has a change to print 'bfdump completed' in a separate line for bfdump, and adjusts the order of the 'done' check so it won't miss the last data.
RM #4368416
=> bfb-install: pack the bf.cfg into the generated BFB

scripts/mlx-mkbfb, third_party/PLDM-unpack/fwpkg_unpack.py
This commit adds ctrl+c handling instead of printing the stack trace.
RM 4368644
=> Add graceful handling of ctrl+c

rshim.spec.in
Our previous selinux fix was only for RHEL 9.5. Needs to add that fix to later RHEL versions.
RM #4362238
=> RPM pkg: Apply selinux workaround to RHEL 9.5 or later

src/rshim.c, src/rshim.h, src/rshim_net.c
Increase network polling interval in low traffic to reduce CPU utilization. This resolves an issue where rshim's CPU utilization on BMC would increase significantly (e.g., from 5% to 16%) due to background CPU load.
RM #4271127
=> Reduce CPU utilization by network optimization

scripts/mlx-mkbfb
This commit breaks the loop when exacting a single image after having found it. It also ports a graceful change to hangle ctrl+C.
RM #4374856
=> mlx-mkbfb: Improve the performance when extracting a single image

scripts/bfb-install
The bfb and rshim options can be input only once. Otherwise error messages should be given.
RM #4187950
=> bfb-install: add validation of bfb and rshim options

scripts/bfb-install
This commit fixes the duplicate trap action that the first definition is overwritten by the second one, thus causing TMP_DIR not cleaned up properly.
RM #4389249
=> bfb-install: cleanup the TMP_DIR

scripts/bfb-install
When NIC_FW is upgraded, it'll be marked as pending and prevents another update before activation. This script reactivates NIC_FW for runtime upgrade to allow multiple updates which is the same behavior as PLDM upgrade from platform BMC..
RM #4403764
=> bfb-install: Reactivate NIC_FW for runtime upgrade

man/bfb-tool.8, scripts/bfb-tool
- Added '--output-format flat' option to create bf-fwbundle BFBs in flat format.
- Enables support for DPU in NIC mode.
=> scripts/bfb-tool: Add flat format support for BFB

scripts/bfb-install
This commit converts bundle BFB to flat BFB when doing runtime upgrade. It could be used by both LFWP (Live Firmware Path) or No-service-interruption Upgrade.
RM #4449636
=> bfb-install: Convert to flat BFB for runtime upgrade

man/bfb-install.8, scripts/bfb-install
This commit adds command syntax for lfwp.
-l | --lfwp: enable lfwp flow
-a | --activate: activate lfwp
If only '--lfwp' is specified, it'll do activation by default unless '--activate=0' is specified.
RM #4449636
=> bfb-install: add command syntax for lfwp

src/rshim.c
Registering EPOLLOUT on timerfd causes epoll_wait() to return immediately since timerfds are always writable. This leads to a busy loop with high syscall frequency and high CPU usage in some cases.
Removing EPOLLOUT allows epoll_wait() to block properly until timer expiration. Verified on BlueField-3: under a certain stress test, CPU usage dropped from 35% to 3%.
RM #[4271227](https://redmine.mellanox.com/issues/4271227)
=> Reduce CPU usage by polling optimization

src/rshim_cmdmode.c
When bfdump succeeds, the return value is 8. It's the result value of write sizeof(uint64_t). This fix sets the return value to 0 after the write is successful.
=> Fix bfdump doesn't return error code in case of success

rshim.spec.in
This commit detects uek64k at build time and sets the is_uek64k flag, so correct dependencies can be used when installing the binary RPM.
RM #4542951
=> Set is_uek64k flag at build time
