- rshim.c
CUSE doesn't support offset in pread(). This commit adds ioctl()
support to access this file in Linux.
> ioctl() support for /dev/rshim0/rshim

- Makefile.freebsd
Signed-off-by: Hans Petter Selasky <hps@selasky.org>
> Update Makefile for FreeBSD.

- rshim.c
- rshim_pcie.c
Signed-off-by: Hans Petter Selasky <hps@selasky.org>
> Compile fixes for 32-bit platforms.

- Makefile.am
- configure.ac
- freebsd/rshim.in
> Add service file for FreeBSD

- man/rshim.8
- src/rshim.h
- src/rshim_fuse.c
- src/rshim_pcie.c
- src/rshim_pcie_lf.c
- src/rshim_usb.c
> misc: Display device version / revision ID

- debian/changelog
- rhel/rshim.spec.in
- rshim.spec.in
- src/rshim.c
This commit fixes several coverity warnings and updates the changelog.
> Fix several coverity warnings

- src/rshim.c
When both USB and pcie_lf start, the pcie_lf will be probed first
since the USB related driver code registers USB hotplug callback
and probes the rshim devices asynchronously. This commit adds a
delay for pcie_lf backend so USB devices could be probed first if
connected.
> Add some delay for the pcie_lf probe

- src/rshim.c
This commit changes the debug level of ""Rshim byte access" to
DEBUG level since it causes confusing for some automation script
during card reset. It also adds optional argument "--nonet" to
skip starting the network interface if needed.
> CHange the debug level of "Rshim byte access widget timeout"

- src/rshim.c
This commit fixes a potential race in rshim_fifo_read() where the
access of read_fifo is not protected by lock. It also adds some
details in the INFO message to identify the rshim.
> Avoid potential race in rshim_fifo_read

- scripts/bfb-install
> bfb-install: fix some typo in help message and add error check

- src/rshim.c
The tmfifo output was stored in a ring buffer. When it's time to
transmit, it calls rshim_fifo_output() to pack data into a buffer,
then calls the backend->write() to write to the fifo which calls
rshim_write_default() for pcie rshim. The buffer will eventually
calls rshim_write_delayed() to process it which checks the available
space before writting to the fifo, and will timeout if no space
in 3 seconds. Once it happens, it'll cause data loss and fifo packet
out-of-sync. It could happen when ARM is too slow (such as during
booting) under external tmfifo network traffic.
This commit fixes the problem by checking the available space in
rshim_fifo_output() when preparing the write buffer. So it won't
have any timeout later.
> Fix potential tmfifo data loss

- src/rshim.c
This commit checks the current attached rshim devices and uses a
large interval for the background timer when there is no rshim
devices. Thus the CPU utilization will be minimum in such case.
> Reduce CPU utilization when there is no rshim device

- src/rshim.c
- src/rshim_usb.c
This commit checks the number of rshim devices at runtime and
disables the background timer if no more devices. Thus the CPU
utilization will be zero due to the epoll(). When USB is
reconnected, an event will be sent to activate the epoll() loop.
So new USB devices could be probed.
> Disable the background timer if no rshim devices

- src/rshim.c
This is a follow-up commit of 05f04595ac0cf5. Instead of adding
delay after the RESET, this commit moves the delay to the USB up
event so it can cover both the SoC and Host side.
> Add a delay after USB probe

- src/rshim_pcie.c
This commit removes 32-bit support for simplicity since the
RSH_BYTE_ACC_xxx registers have been removed from BF3 thus needs
to be reworked anyway. It can be added back when needed.
> PCIe: Remove 32-bit support

- src/rshim_pcie.c
This commit adjusts the logic to try UIO if memory-map of VFIO
fails. Thus direct-map should be tried last.
> Fallback to UIO if VFIO failed

- src/rshim_pcie.c
This commit fixes an interrupt missing issue reported druing
mlxfwreset. The cause is due to race of intr_fd being read and
closed. There are different ways to solve it. A simple and
efficient way here is to keep the intr_fd.
> Keep intr_fd during rshim_pcie disable/enable

- src/rshim_pcie.c
This commit changes the global memory mapping method to be per-
device, so if one device changes it won't affect the others. It
fixes a memory-mapping issue found on host with multiple DPU cards.
> Use per-device memory-map mode

- src/rshim_pcie.c
> Fix several compiling issues for FreeBSD

- src/rshim.c
The rshim_work_fd is a pipe polled by the main thread and used by
other threads to wake up the main thread by writting the bd index.
Previously the index is written as 4 bytes which is not efficient
and could potentially cause issues if some of the byte is missing
somhow. Since the driver only supports up to 64 rshim devices, this
commit changes to write one byte instead of 4 bytes to be more
reliable.
> Optimize the rshim_work_fd

- src/rshim.c
- src/rshim.h
- src/rshim_fuse.c
- src/rshim_log.c
- src/rshim_pcie.c
- src/rshim_pcie_lf.c
- src/rshim_usb.c
Mustang hardware supports 1B, 2B, 4B and 8B USB transfers.
> support other transfer sizes: 1B, 2B, 4B on top of 8B

- src/rshim.c
> Fix warnings for compiling on 32-bit BMC

- src/rshim_pcie.c
When both VFIO/UIO memory mapping and direct mapping co-exist on host with multiple rshim devices, the direct-mapped rshim will be affected when doing the VFIO bind by adding the 'vendor device' ID into sysfs new_id, which adds the direct-mapped rshim PF into VFIO as well due to 'no driver' is used.
This commit writes a faked 'rshim' string into the sysfs 'driver_override' for rshim PF to prevent other drivers from taking over it while being used.
> pcie: Support mixed vfio and direct mapping mode

- src/rshim.c
- src/rshim.h
- src/rshim_log.c
- src/rshim_net.c
- src/rshim_regs.c
- src/rshim_regs.h
This commit updates the common files to use GPL-2.0/BSD-3-Clause dual liense.
> Update common files to dual-license

- src/rshim_usb.c
Boot stream timeout or data corruption were observed for cases where booting is very slow, such as due to slow DDR training or NIC_FW upgrade in UEFI capsule. This commit has the following fixes for this issue.
- Set the timeout value to be bd->boot_timeout instead of fixed 60 seconds. So it could be tuned by BOOT_TIMEOUT in /dev/rshim0/misc.
- Check the available space against the actually needed space 'count'.
- Return the actual transmitted bytes in case of timeout.
> rshim/usb: fix data corruption when boot streaming is slow

- src/rshim_pcie.c
This commit has changes to handle the RSHIM_PCIE_RST_STATE_START event, which is needed by the new NIC FW_RESET flow which takes longer now due to the graceful shutdown action to DPU(ARM).
> Fix interrupt handling for NIC FW_RESET

- src/rshim_pcie.c
This commit removes the version 0 support for NIC FW_RESET according to Arch decision.
> Remove version 0 support for NIC FW_RESET

- src/rshim.c
This commit has some fixes for potential high CPU utilization.
- Add small loop delay in function rshim_fd_full_read()/ rshim_fd_full_write().
- Check checksum (either 0 or valid checksum) for Rx message.
- Check message length for Rx message.
RM #3613738
> Several robust fixes

- src/rshim.c
- src/rshim.h
- src/rshim_fuse.c
This commit adds debug code which could be sent to enable debugging at runtime.
RM #3693641
> Allow runtime debug code

- src/rshim_pcie.c
NIC_FW changed the timeout value recently to be 3 seconds when waiting for link reset. Since rshim driver was using 2 seconds timeout, it causes potential race after rshim driver timeout and starts to send traffic while NIC_FW is not ready yet. This race causes potential PCIe completion timeout and host crash. This commit adjusts the delay time in rshim driver to avoid such issue.
RM #3751960
> rshim_pci: adjust delay time for nic_fw reset

- configure.ac
- debian/changelog
- rhel/rshim.spec.in
- rshim.spec.in
> Update version to 2.0.27

- src/rshim.c
- src/rshim.h
- src/rshim_fuse.c
- src/rshim_pcie.c
https://redmine.mellanox.com/issues/3870080
Also, add workarounds RSHIM PF write/read bugs.
> Prevent bmc host rshim running simultaneously

- src/rshim.c
- src/rshim_usb.c
This commit has the following robust fixes for rshim over USB.
- In rshim_fifo_output(), the actual Tx available size should be used instead of the maximum WRITE_BUF_SIZE, or else it could cause data loss on slow USB.
- In rshim_notify(), use asynchronous rshim_work_signal() rather than direct function call to avoid race condition when rshim_notify() is called from USB completition callback.
- In rshim_usb_fifo_read_callback(), use pthread_mutex_trylock() to avoid potential dead lock.
> Some robust fixes for rshim over USB

- configure.ac
- debian/changelog
- rhel/rshim.spec.in
- rshim.spec.in
> Update version to 2.0.35

- src/rshim.c
> Fix compiling issue for FreeBSD

- man/rshim.8
- src/rshim.c
[RM 3991837](https://redmine.mellanox.com/issues/3991837)
> fix: add missing --force in help menu

- scripts/bfb-install
> bfb-install: adjust the log file to be per rshim

- src/rshim_pcie.c
This commit adds VFIO support for Bluefield-3.
RM #4015958
> pcie: Add VFIO support for Bluefield-3

- configure.ac
- debian/changelog
- rhel/rshim.spec.in
- rshim.spec.in
RM #4005329
RM #4005240
RM #4015958
> Update version to 2.0.39

- debian/postinst
> Fix rshim deb package for DOCA build on Ubuntu

- src/rshim.c
- src/rshim_fuse.c
- src/rshim_log.c
- src/rshim_net.c
- src/rshim_pcie.c
- src/rshim_usb.c
This commit cleans up the debug/syslog messages, and add 'rshim<N>' when possible.
> Cleanup rshim debug/syslog messages

- man/rshim.8
- src/Makefile.am
- src/rshim.c
- src/rshim.h
- src/rshim_cmdmode.c
- src/rshim_fuse.c
- src/rshim_log.c
- src/rshim_regs.h
- src/rshim_usb.c
This pull request has the two commits:
Add support for command mode
Fix some coding style issue
> Add command mode support

- src/rshim.c
- src/rshim.h
- src/rshim_fuse.c
This pull request contains changes to revert commit 75d0d3bef258 for RM #4049579.
It also fixes two compiling warnings.
> Revert the 2-second delay for RM #4049579

- src/rshim.c
> Improve access_check() to reduce likelihood of race condition.

- src/rshim.c
> Reduce the access_check() wait time

- rhel/rshim.spec.in
- rshim.spec.in
> Abort rshim rpm installation if no cuse.ko found

- src/rshim.c
> Make rshim run in single instance

- rhel/rshim.spec.in
- rshim.spec.in
This reverts commit a91c6305012e9baa8c205ef28b7c03a9cb23b415.
> Revert "Abort rshim rpm installation if no cuse.ko found"

- etc/rshim.conf
- man/rshim.8
- src/rshim.c
- src/rshim.h
- src/rshim_fuse.c
- src/rshim_usb.c
> Add USB_TIMEOUT to misc and conf settings

- src/rshim.h
- src/rshim_fuse.c
- src/rshim_usb.c
> Allow 0 to restore USB_TIMEOUT default value

- scripts/bfb-install
> bfb-install: Handle PF1 bind/unbind in NIC mode

- Makefile.am
- man/Makefile.am
- man/mlx-mkbfb.1
- rhel/rshim.spec.in
- rshim.spec.in
- scripts/mlx-mkbfb
Based on commit-id a9708244b22478f5c984c7ab7db67c8176642c34 from github.com/Mellanox/bfscripts.git
RM #4247298
> Added mlx-mkbfb

- Makefile.am
- rhel/rshim.spec.in
- rshim.spec.in
- third_party/PLDM-unpack/License-MIT-fwpkg-unpack.txt
- third_party/PLDM-unpack/README.md
- third_party/PLDM-unpack/fwpkg_unpack.py
Based on commit-id a9708244b22478f5c984c7ab7db67c8176642c34 from https://github.com/NVIDIA/PLDM-unpack.git
RM #4330049
> Add fwpkg_unpack

- scripts/bfb-install
- scripts/mlx-mkbfb
- third_party/PLDM-unpack/fwpkg_unpack.py
- PLDM support
- Only trigger SWINT2.BIT2 for upgrade in NIC mode
- No bind/unbind for runtime upgrade
- Fetch latest change in mlx-mkbfb for NIC_FW
RM #4330047
> bfb-install: Enhancement for runtime upgrade

- Makefile.am
- man/Makefile.am
- man/bfb-tool.8
- rshim.spec.in
- scripts/bfb-tool
Tool for extracting and repackaging BFBs.
bfb-tool <action> --bfb <BFB> --psid <PSID>|--opn <OPN>|--all [-p|--profile <Profile>] [--output-dir <dir>] [-v|--verbose]
> Added bfb-tool script

- src/rshim_cmdmode.c
This commit fixes the register read/write with rshim command line. rshim_setup() was not called earlier for such case during code cleanup. The fix is to do it in rshim_rw() to avoid such issue for all other commands.
> Fix the rshim command line for register read/write

- src/rshim_pcie.c
Coverity CID: 800748
https://coverity.mellanox.com/reports.htm#v10929/p10018/fileInstanceId=324630952&defectInstanceId=113120716&mergedDefectId=800748
RM 4408445
https://redmine.mellanox.com/issues/4408445
> Fix a potentially unintialized variable

- .github/workflows/ci.yml
[RM #4435519](https://redmine.mellanox.com/issues/4435519)
> Fix transient pipeline error caused by apt update

- .github/workflows/ci.yml
[RM #4362233](https://redmine.mellanox.com/issues/4362233)
> Disable LTO build option in github CI

- man/bfb-install.8
- scripts/bfb-install
This commit has some fixes for 91385a62ea08.
RM #4449636
> bfb-install: BFB format conversion for runtime upgrade

- scripts/bfb-install
- scripts/bfb-tool
> Added support for bf-fwbundle per OPN

- src/rshim.c
- src/rshim.h
- src/rshim_pcie.c
> Deregister driver (vfio or uio) when not in use
